version: 2.1

jobs :
  build :
    docker :
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: echo "npm installing"
        - run: npm install
        - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test